# Message sends to the player when he becomes frozen or unfrozen
notification_message:
  frozen: "You have been frozen"
  unfrozen: "You have been unfrozen"
  
particle_enable: true
sound_enable: true