# Message sends to the player when he becomes frozen or unfrozen
# You can use color codes
notification_message:
  frozen: "&aYou have been frozen"
  unfrozen: "&aYou have been unfrozen"
  
particle_enable: true

# If you server run spigot/bukkit 1.13.x, turn let sound on false
sound_enable: false