main: net.sweetmimike.advancedfreeze.Main
version: 1.0
name: AdvancedFreeze
author: Sweetmimike
commands:
  freeze:
    description: Freeze the players
    permission: af.freeze
  unfreeze:
    description: Unfreeze the players
    permission: af.unfreeze
    
permissions:
  af.*:
    description: Gives you all the permissions
    default: op
    children:
      af.freeze : true
      af.unfreeze: true
      af.bypass: true
      af.reload: true
      af.help: true
  af.freeze:
    description: Allows you to freeze players
    default: false
  af.unfreeze:
    description: Allows you to unfreeze players
    default: false
  af.bypass:
    description: Allows you to never be frozen
    default: false
  af.reload:
    description: Allows you to reload the config file
    default: op
  af.help:
    description: Allows you to show the help